### ISSUE TITLE
bagaimana cara menggunakannya ?

### ISSUE THREAD

**Issue by agus3winarno** [diskominfodiy/sebaran-covid19#2]
hi tim diskominfodiy, bagaimana cara menggunakan repo ini?

**Comment by rrozaq** [comment]
> hi tim diskominfodiy, bagaimana cara menggunakan repo ini?

hallo @agus3winarno 
untuk cara penggunaanya bisa ikuti langkah-langkah berikut

- > Jalankan _composer install_ di terminal
- > rename _.env.example_ menjadi _.env_ , Isikan konfigurasi URL dan database pada file .env
- > ketik di terminal : _php artisan migrate_
- > ketik di terminal : _php artisan db:seed_
- > ketik di terminal : _php artisan serve_ , untuk menjalankan di komputer local

**Comment by rrozaq** [comment]
> hi tim diskominfodiy, bagaimana cara menggunakan repo ini?

hallo @agus3winarno 
untuk cara penggunaanya bisa ikuti langkah-langkah berikut

**Clone atau Download Repo ini**
- > $ _composer install_
- > rename _.env.example_ menjadi _.env_ , Isikan konfigurasi URL dan database pada file .env
- > $ _php artisan migrate_
- > $ _php artisan db:seed_

Untuk menjalankan testing di local
- > $ _php artisan serve_

**Comment by wendyadi** [comment]
Sudah dijelaskan di README.md ya
